### ISSUE TITLE
practica 3

### ISSUE THREAD

**Issue by YulianaMorales18** [SistemasTecTlaxiaco/practica-6-relaciones-funciones-y-plano-cartesiano-equipo-f4#1]
[Practica 3 1AS.pdf](https://github.com/user-attachments/files/17158614/Practica.3.1AS.pdf)

**Comment by irwingsael** [comment]
Exposición de Ideas Centrales:5/5
Redacción y Ortografía:5/5
Presentación visual:5/5
Referencias:5/5
Calificación Final:20/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
